### ISSUE TITLE
Build broken after in cheriabi_sysstubs.h

### ISSUE THREAD

**Issue by RichardsonAlex** [CTSRD-CHERI/cheribsd#170]
I looked at which commits changed this file since my last rebuild and git revert bafd8faa734c17b371941d408026bce0afac861e fixes it for me

Build breaks in cheri_system.c:
```
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:65:1: error: expected expression
SYS_STUB(, int, syscall,
^
/home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:196:55: note: expanded from macro 'SYS_STUB'
        checkfunc = (int(*)_protoargs_chk)syscall_checks[_num];         \
                                                             ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:837:31: error: conflicting types for 'readv'
SYS_STUB_ARGHASPTRS(120, int, readv,
                              ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/sys/uio.h:116:9: note: previous declaration is here
ssize_t readv(int, const struct iovec *, int);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:847:31: error: conflicting types for 'writev'
SYS_STUB_ARGHASPTRS(121, int, writev,
                              ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/sys/uio.h:117:9: note: previous declaration is here
ssize_t writev(int, const struct iovec *, int);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:1187:20: error: conflicting types for 'getrlimit'
SYS_STUB(194, int, getrlimit,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/sys/resource.h:185:5: note: previous declaration is here
int     getrlimit(int, struct rlimit *);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:1197:20: error: conflicting types for 'setrlimit'
SYS_STUB(195, int, setrlimit,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/sys/resource.h:188:5: note: previous declaration is here
int     setrlimit(int, const struct rlimit *);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:1637:35: error: conflicting types for 'preadv'
SYS_STUB_ARGHASPTRS(289, ssize_t, preadv,
                                  ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/sys/uio.h:119:9: note: previous declaration is here
ssize_t preadv(int, const struct iovec *, int, off_t);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:1647:35: error: conflicting types for 'pwritev'
SYS_STUB_ARGHASPTRS(290, ssize_t, pwritev,
                                  ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/sys/uio.h:120:9: note: previous declaration is here
ssize_t pwritev(int, const struct iovec *, int, off_t);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:2707:20: error: conflicting types for 'audit'
SYS_STUB(445, int, audit,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/bsm/audit.h:307:5: note: previous declaration is here
int     audit(const void *, int);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:2717:20: error: conflicting types for 'auditon'
SYS_STUB(446, int, auditon,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/bsm/audit.h:308:5: note: previous declaration is here
int     auditon(int, void *, int);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:2737:20: error: conflicting types for 'setauid'
SYS_STUB(448, int, setauid,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/bsm/audit.h:311:5: note: previous declaration is here
int     setauid(const au_id_t *);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:2757:20: error: conflicting types for 'setaudit'
SYS_STUB(450, int, setaudit,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/bsm/audit.h:313:5: note: previous declaration is here
int     setaudit(const struct auditinfo *);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:2767:20: error: conflicting types for 'getaudit_addr'
SYS_STUB(451, int, getaudit_addr,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/bsm/audit.h:314:5: note: previous declaration is here
int     getaudit_addr(struct auditinfo_addr *, int);
        ^
In file included from /home/alr48/cheri/sources/cheribsd/lib/libcheri/cheri_system.c:264:
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/compat/cheriabi/cheriabi_sysstubs.h:2777:20: error: conflicting types for 'setaudit_addr'
SYS_STUB(452, int, setaudit_addr,
                   ^
/home/alr48/cheri/build/cheribsd-obj-256/mips.mips64/home/alr48/cheri/sources/cheribsd/tmp/usr/include/bsm/audit.h:315:5: note: previous declaration is here
int     setaudit_addr(const struct auditinfo_addr *, int);
        ^
13 errors generated.
*** [cheri_system.o] Error code 1

bmake[4]: stopped in /home/alr48/cheri/sources/cheribsd/lib/libcheri
1 error

bmake[4]: stopped in /home/alr48/cheri/sources/cheribsd/lib/libcheri
*** [lib/libcheri__L] Error code 2

bmake[3]: stopped in /home/alr48/cheri/sources/cheribsd
1 error

bmake[3]: stopped in /home/alr48/cheri/sources/cheribsd
*** [libraries] Error code 2

bmake[2]: stopped in /home/alr48/cheri/sources/cheribsd
1 error

bmake[2]: stopped in /home/alr48/cheri/sources/cheribsd
```
